### ISSUE TITLE
Adding IP-Adress

### ISSUE THREAD

**Issue by horenzloerner** [mb-software/homeassistant-powerbrain#87]
Hi,

i am rather new to homeassistant, so this could be a newbie question. I just installed the Powerbrain Add-On via HACS. But i can't access the Configuration UI to enter my IP of the wallbox as shown in the despcripton. How can i "trigger" the UI, or can i also add the IP via SSH?

Best

**Comment by mb-software** [comment]
Hi,
in your HA devices and integrations configuration just click on "add integration" and select the cFos Powerbrain integration, which should appear in the list once successfully installed from HACS.
I'm closing this issues since it seems to be more of a general HA question rather than an issue of this integration.
